version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - export ZIP_FILE=hello-angular-$CODEBUILD_RESOLVED_SOURCE_VERSION.zip
      
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
     commands:
      - echo Build completed on `date`
      - zip -r $ZIP_FILE dist/*
      - aws s3 cp $ZIP_FILE s3://guy-chauliac-build-artefacts/$ZIP_FILE 
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes