AWSTemplateFormatVersion: 2010-09-09
Parameters:
  bucketName:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref bucketName